--- 
name: nsx-lb-mon
display-name: "Stylebook for loadbalancer configuration from NSX"
description: "This is the root stylebook that can support all default configurations from NSX that are passed through NETX protocol. It can be  used for only implementing serviceprofile payload part of the NETX LB creation. This will be a private stylebook and will be used for NSX integration. It will implement a simple LB configuration by creating a cs vserver with one lb vserver"
namespace: com.citrix.adc.stylebooks
schema-version: "1.0"
private: true
version: "1.0"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "10.5"
  - 
    namespace: com.citrix.adc.stylebooks
    prefix: stlb
    version: "1.0"
  - 
    namespace: com.citrix.adc.commontypes
    prefix: cmtypes
    version: "1.0"
substitutions:
  lb-servicetype[]:
    http: HTTP
    https: SSL_BRIDGE
    tcp: TCP
    udp: UDP
  algorithm[]:
    round-robin: ROUND-ROBIN
    ip-hash: SRCIPDESTIPHASH
    leastconn: LEASTCONNECTION
    uri: TOKEN
    httpheader: TOKEN
    url: URLHASH
parameters-default-sources:
  - stlb::nsx-root-params
components:
  - 
    name: default-lbvserver
    type: "ns::lbvserver"
    description: "Builds a default lb vserver with a servicegroup for the vendorPool object passed in virtualServerDefinition"
    properties:
      name: "\"nsx-lbvserver-default-\" + $parameters.serviceProfileBinding.virtualServerDefinition.virtualServerId"
      servicetype: $substitutions.lb-servicetype($parameters.serviceProfileBinding.virtualServerDefinition.vendorApplicationProfile.protocol)
      ipv46: 0.0.0.0
      port: 0
    components: 
      - 
        name: svcgrp
        type: "ns::servicegroup" 
        properties: 
          servicegroupname: "\"nsx-sg-default-\" + $parameters.serviceProfileBinding.virtualServerDefinition.virtualServerId"
          servicetype: $parent.properties.servicetype
        components: 
          - 
            name: lbvserver-svg-binding
            type: "ns::lbvserver_servicegroup_binding"
            condition: $parameters.serviceProfileBinding.virtualServerDefinition.vendorPool.vendorMember
            properties: 
              name: $parent.parent.properties.name
              servicegroupname: $parent.properties.servicegroupname
          - 
            name: svg-members
            type: "ns::servicegroup_servicegroupmember_binding"
            condition: $parameters.serviceProfileBinding.virtualServerDefinition.vendorPool.vendorMember
            repeat: $parameters.serviceProfileBinding.virtualServerDefinition.vendorPool.vendorMember
            repeat-item: vendorMember
            properties: 
              ip: $vendorMember.ipAddress
              port: $vendorMember.vendorServicePort.port
              servicegroupname: $parent.properties.servicegroupname
  -
    name: monitors-comp
    type: ns::lbmonitor
    condition: $parameters.serviceProfileBinding.virtualServerDefinition.vendorPool.vendorServiceMonitorPort.vendorHealthcheck.mode
    description: "Builds a NetScaler monitor object and binds them to the servicegroup created for vendorPool"
    properties:
        monitorname: "\"nsx-mon-default-\" + $parameters.serviceProfileBinding.virtualServerDefinition.virtualServerId"
        type: $substitutions.lb-servicetype($parameters.serviceProfileBinding.virtualServerDefinition.vendorPool.vendorServiceMonitorPort.vendorHealthcheck.mode)
        interval?: $parameters.serviceProfileBinding.virtualServerDefinition.vendorPool.vendorServiceMonitorPort.vendorHealthcheck.interval
        resptimeout?: $parameters.serviceProfileBinding.virtualServerDefinition.vendorPool.vendorServiceMonitorPort.vendorHealthcheck.timeout
    components:
      -
        name: monitor-svcg-binding-comp
        type: ns::servicegroup_lbmonitor_binding
        condition: $parameters.serviceProfileBinding.virtualServerDefinition.vendorPool.vendorServiceMonitorPort.vendorHealthcheck
        properties:
          servicegroupname: $components.default-lbvserver.components.svcgrp.properties.servicegroupname
          monitor_name: $parent.properties.monitorname             
  - 
    name: csvservercomp
    type: "ns::csvserver" 
    description: "Builds a default cs vserver with the endpoint IP address+port and binds it to the default LB vserver created for this config"
    properties: 
      ipv46: $parameters.serviceProfileBinding.virtualServerDefinition.ipAddress
      name: "\"nsx-csvserver-\" + $parameters.serviceProfileBinding.virtualServerDefinition.virtualServerId"
      port: $parameters.serviceProfileBinding.virtualServerDefinition.vendorApplicationProfile.port
      servicetype: $substitutions.lb-servicetype($parameters.serviceProfileBinding.virtualServerDefinition.vendorApplicationProfile.protocol)
    components: 
      - 
        name: default_cslb
        type: "ns::csvserver_lbvserver_binding"
        properties: 
          lbvserver: $components.default-lbvserver.properties.name
          name: $parent.properties.name       
outputs: 
  - 
    name: csvserver
    value: $components.csvservercomp
    description: "Exposes the created CS vserver component"
  - 
    name: lbvserver
    value: $components.default-lbvserver.properties.name
  - 
    name: service-group
    value: $components.default-lbvserver.components.svcgrp