name: ssl-config-params
namespace: com.citrix.adc.commontypes
version: "1.0"
display-name: SSL Config Parameters
private: true
schema-version: "1.0"
import-stylebooks: 
  - 
    namespace: com.citrix.adc.commontypes
    version: "1.0"
    prefix: cmtypes
parameters:
    -
        name: ssl-config
        label: SSL Parameters Config Section
        type: object
        gui: 
            collapse_pane: true  
        parameters:
          -
            name: ssl-ciphers
            label: SSL Ciphers
            type: string[]
            allowed-values:
              - TLS1-AES-256-CBC-SHA
              - SSL3-EDH-DSS-DES-CBC3-SHA
              - TLS1-DHE-DSS-AES-256-CBC-SHA
              - SSL3-EDH-RSA-DES-CBC3-SHA
              - TLS1-DHE-RSA-AES-256-CBC-SHA
              - TLS1-DHE-RSA-AES-128-CBC-SHA
              - TLS1-AES-128-CBC-SHA
              - TLS1-DHE-DSS-RC4-SHA
              - TLS1-DHE-DSS-AES-128-CBC-SHA
            required: true
          -
            name: ssl-protocols
            label: SSL Protocols
            type: object
            parameters:
              -
                name: ssl3
                label: SSL 3
                type: boolean
                default: false
              -
                name: tls1
                label: TLS 1
                type: boolean
                default: true
              -
                name: tls11
                label: TLS 1.1
                type: boolean
                default: true
              -
                name: tls12
                label: TLS 1.2
                type: boolean
                default: true