--- 
name: vserver-tmtrafficpolicies-bindings
display-name: VServer to TM Traffic Policies Binding Stylebook
description: This StyleBook binds a vserver (LB or CS) to a TM traffic policy or policy label
namespace: com.citrix.adc.stylebooks
private: true
schema-version: "1.0"
version: "1.0"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "10.5"
  - 
    namespace: com.citrix.adc.commontypes
    version: "1.0"
    prefix: cmtypes    
parameters-default-sources:
  - cmtypes::vserver-policies-bindings-params
substitutions:
  gotopriorityexpression:
    true: NEXT
    false: END
  priority(ndx): 10 + ($ndx * 10)
components:
  - 
    name: lbvserver-tmtraffic-policy-binding-comp
    type: ns::lbvserver_tmtrafficpolicy_binding
    description: Component for binding TM traffic policies and lbvserver
    condition: $parameters.vserver-type == LBVSERVER
    repeat: $parameters.policies
    repeat-item: policy
    repeat-index: ndx
    properties: 
      name: $parameters.vserver-name
      policyname: $policy.name
      bindpoint: $policy.bind-point
      priority: $substitutions.priority($ndx)
      gotopriorityexpression: $substitutions.gotopriorityexpression[$policy.continue]
  - 
    name: csvserver-tmtraffic-policy-binding-comp
    type: ns::csvserver_tmtrafficpolicy_binding
    description: Component for binding TM traffic policies and csvserver
    condition: $parameters.vserver-type == CSVSERVER
    repeat: $parameters.policies
    repeat-item: policy
    repeat-index: ndx
    properties: 
      name: $parameters.vserver-name
      policyname: $policy.name
      bindpoint: $policy.bind-point
      priority: $substitutions.priority($ndx)
      gotopriorityexpression: $substitutions.gotopriorityexpression[$policy.continue]
